Add test
fileverse/HeartBitSDK pull request #60
Opened 2024-04-08 06:04 UTC by Joshua-onwuzu

- [ ] Bug fix 
- [ ] New feature 
- [x] Chore 
- [ ] Breaking change 
- [ ] There is an open issue which this change addresses
- [ ] My commits follow the [Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] My change requires a change to Typescript typings.
  - [ ] I have updated the typings accordingly.

2024-04-08 06:24 UTC, nadeem-fileverse requested changes
PTAL

2024-04-08 06:48 UTC, Joshua-onwuzu commented on packages/heartbit-core/src/test/mockData.ts
> +    message: "p6f7gr-5173.csb.app wants you to sign in with your Ethereum account:\n0x852bd84A4dcDc150648AE4e8D6D6e59b1797c86f\n\nHello World!\n\nURI: https://p6f7gr-5173.csb.app\nVersion: 1\nChain I
done

2024-04-22 05:37 UTC, nadeem-fileverse requested changes
PTAL

2024-04-22 05:37 UTC, nadeem-fileverse commented on .github/workflows/test.yml
> +      - name: 🧩 Install Dependencies
build can be made from the root command i think check for build command in root package.json

2024-04-22 05:37 UTC, nadeem-fileverse commented on .github/workflows/test.yml
> +      - name: 🧪 Run Tests
update for heartbit react

2024-06-11 13:03 UTC, closed without merging